### ISSUE TITLE
Cosmetic Change Request

### ISSUE THREAD

**Issue by pi-plates** [Harsch-Systems/node-red-contrib-pi-plates#25]
This really doesn't qualify as an issue but I would like to change the following items:
1) Palette color changed to #87A980 - this is closer to the color palette used on the Pi-Plate web site
2) Remove the unnecessary "pp" prefix on all of the node names
3) Right justify the node icon on output nodes DOUT, LED, DAC, and RELAY.
4) Use more intuitive icons for the nodes instead of the default file.svg. Some can be in the standard set, one can be part of the Font Awesome 4.7 collection (THERMO, TEMP), and a couple could be custom (ADC and DIN). I would be happy to create these.

I would be happy to make all of these changes to the node HTML files if it is agreeable.

**Comment by mharsch** [comment]
1,3, and 4 all sound fine and I'd be happy to merge any of your proposed changes.

The node names can't be changed without breaking existing flows.  However, you may be able to partially achieve the aesthetic change you're looking for by setting the Palette Label property.

**Comment by pi-plates** [comment]
How are these uploaded to the node-red repository?

**Comment by mharsch** [comment]
it's a 2 step process, first you publish to npm via the 'npm publish' command, then you login to the flows.nodered.org site as the same github repo owner user and click the 'check for new version' link.

I've just published the above changes as part of the new version 0.1.6

**Comment by pi-plates** [comment]
Thanks, Mike.
