### ISSUE TITLE
PWM Control DACQ2 Plate

### ISSUE THREAD

**Issue by reisingera03** [Harsch-Systems/node-red-contrib-pi-plates#27]
able to control PWM using the DAQC2 plate

**Comment by mharsch** [comment]
we need a node that exposes setPWM and one for getPWM.  The code is already there in the underlying node-pi-plates layer (but note that it needs testing and there's at least one typo that needs to be fixed for this functionality to work).

**Comment by mharsch** [comment]
This was implemented back in Nov 2021.
