### ISSUE TITLE
Set thermocouple type (K or J) on Thermo Plate inputs

### ISSUE THREAD

**Issue by j1303** [Harsch-Systems/node-red-contrib-pi-plates#33]
There is a `setTYPE` function available for the Thermo Plate that allows you to switch between a type K and type J thermocouple. Would it be possible for you to add this functionality to your node?

According to the [documentation](https://pi-plates.com/thermoplate-users-guide/):

> setTYPE(addr,channel,type) – sets the thermocouple type for a specific channel. Since this only applies to thermocouple inputs, an error message will be generated if the channel argument is not between 1 and 8.

> type: the THERMOplate can measure temperature using both K type and J type thermocouples. Valid arguments are ‘k’ and ‘j’. Be sure and include the quotation marks.

**Comment by mharsch** [comment]
Thank you for pointing this out.  I've added the type setting feature for THERMO nodes (TC1-8) in d0678fbe4d3ed7da7b2396df68b784ea9177d638 and published to npm in version 0.2.3.
