### ISSUE TITLE
ppTEMP node

### ISSUE THREAD

**Issue by Murray274** [Harsch-Systems/node-red-contrib-pi-plates#6]
I am receiving a value when sending DAQC.getTEMP(0,0,"'c') using python on my Raspberry Pi with a DAQCplate fitted.
Notsure hoe to get the ppTEMP node to operate so I inject a value to the node and look for something using a debug node. 
Ehen I inject mannually I see nothing in the debug area but recieve a "Lost connection to server   Reconnecting" for each injection.
On the Node Red console I see the following:

stderr: Traceback (most recent call last):
  File "/home/pi/.node-red/node_modules/pi-plates/plate_io.py", line 3, in <module>
    import piplates.DAQCplate as DP
ImportError: No module named piplates.DAQCplate

What have I got wrong?

Many thanks

Murray

**Comment by mharsch** [comment]
Which version of python are you using when you test DAQCplate.getTEMP()?  When you installed the pi-plates package, did you use pip or pip3?  If you're using python3, could you try installing the python2.7 pi-plates package and see if that works?

**Comment by mharsch** [comment]
Also, is the pi-plate a DAQC or a DAQC2 plate?

**Comment by Murray274** [comment]
I have reloaded the set of pi-plate nodes and the issue is resolved. I also has intermitent reply from the TEMP node but I have itretriving the temperature every one minute in Node Red and after 5 minutes of intermitent reading it has settled down and the readings are without fault. 
Thank you for your assistance.
